services:
  config-init:
    image: ghcr.io/yewfence/infisical-config-init:latest
    # 开发时可本地构建
    build: .
    environment:
      # 辅助命令的输出路径格式为相对目录还是绝对目录
      # - OUTPUT_MODE=absolute
      - OUTPUT_MODE=relative
      - PROJECT_DIR=${PWD}
    volumes:
      - ./config.yaml:/input/config.yaml:ro
      - generated-config:/output
      # 自动识别服务名时需要载入凭证
      - ./client-id:/config/client-id:ro
      - ./client-secret:/config/client-secret:ro

  infisical-agent:
    # 个人修复版本，详细信息见 README.md
    image: ghcr.io/yewfence/infisical-cli:latest
    # 官方 CLI 镜像
    # image: infisical/cli:latest
    container_name: infisical-agent
    restart: always
    command: agent --config=/generated/config.yaml
    depends_on:
      config-init:
        condition: service_completed_successfully
    volumes:
      - generated-config:/generated:ro
      - ./client-id:/config/client-id:ro
      - ./client-secret:/config/client-secret:ro
      - ./secrets:/infisical-secrets

volumes:
  generated-config:
